version: "3.7"
services: 

    model:
        build: "./models"
        container_name: arangodb_conatiner
        volumes: 
            - ./models/data:var/lib/arangodb
        restart: always
    controller:
        build: "./controllers"
        container_name: java_container
        restart: always
        depends_on:
            - model
    view:
        build: "./views"
        container_name: vueJs_container
        restart: always
        ports: 
            - "80:80"
        depends_on:
            - model 
            - controller
        